consoles:
  '0':
    controls:
      - name: accelerate
        type: control-button
        label: accelerate
        action: accelerate
        bindActive: isAccelerating
      - name: decelerate
        type: control-button
        label: decelerate
        action: decelerate
        bindActive: isDecelerating
      - name: em_stop
        type: control-button
        label: "em stop"
        action: em_stop
      -
        name: position_x
        type: control-labeled-data
        label: X-Pos
        bindValue: position_x
        decimals: 2
      -
        name: position_y
        type: control-labeled-data
        label: Y-Pos
        bindValue: position_y
        decimals: 2
    data:
        position_x: "@position[0]"
        position_y: "@position[1]"
        isAccelerating: "@isAccelerating"
        isDecelerating: "@isDecelerating"
  '1':
    controls:
      -
        name: main_screen
        type: main-screen
        bindShipX: position_x
        bindShipY: position_x
    data:
        position_x: "@position[0]"
        position_y: "@position[1]"
