terminals:
  - name: general
    controls:
      -
        name: accelerate
        type: control-button
        label: accelerate
        action: accelerate
        bindActive: isAccelerating
      -
        name: em_stop
        type: control-button
        label: "em stop"
        action: em_stop
      -
        name: position_x
        type: control-labeled-data
        label: X-Pos
        bindValue: position_x
        decimals: 2
      -
        name: position_y
        type: control-labeled-data
        label: Y-Pos
        bindValue: position_y
        decimals: 2
      -
        name: heading
        type: control-labeled-data
        label: Heading
        bindValue: angle
      -
        name: energy
        type: control-labeled-data
        label: Energy
        bindValue: energy
    data:
        position_x: "@body.p.x"
        position_y: "@body.p.y"
        isAccelerating: "@isAccelerating"
        angle: "@body.a*180/3.141592"
        energy: "@cm.bus.available_energy"
  - name: main screen
    controls:
      -
        name: main_screen
        type: main-screen
        bindShipX: position_x
        bindShipY: position_x
    data:
        position_x: "@body.p.x"
        position_y: "@body.p.y"
